### DISCUSSION TITLE
How wrong???

### DISCUSSION THREAD

**Discussion by UsefullProgrammer** [cheshire-cat-ai/core#1047] [General]
I have set cheshire i think just and set ollama on docker i think just but not work, is in same machine.
https://i.imgur.com/zJPPVii.png
https://i.imgur.com/ynS1AKf.png
https://i.imgur.com/QXe9Fu6.png
https://i.imgur.com/MTiALSr.png

**Comment by lucagobbi** [comment]
> I have set cheshire i think just and set ollama on docker i think just but not work, is in same machine. https://i.imgur.com/zJPPVii.png https://i.imgur.com/ynS1AKf.png https://i.imgur.com/QXe9Fu6.png https://i.imgur.com/MTiALSr.png

They're on the same machine but are they on the same docker network? Did you setup a compose for those or are they just separated containers?

If you want to setup a common specific network for those you should do that in compose.yml, something like:

```yaml
services:
  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - 1865:80
      - 5678:5678
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
    networks:
      - cat_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - cat_network

networks:
  cat_network:
    driver: bridge
```

If they are separated but on the same host you can leverage the host network using `host.docker.internal` instead of localhost from one container to another
