### DISCUSSION TITLE
Problems connecting to ollama

### DISCUSSION THREAD

**Discussion by b1tfl0w** [cheshire-cat-ai/core#1066] [Q&A] [answered]
I have a connection problem with ollama, I've just installed cheshire-cat-ai on my debian server (local server in my home, same network) I've set up ollama address as `http://127.0.0.1:11434` but I get `[Errno 111] Connection refused`.
Ollama is installed on the same machine (not with docker), I also have open-webui installed with docker which works with ollama, I remember I had to add this variable `Environment="OLLAMA_HOST=0.0.0.0"` in systemd ollama service file, otherwise open-webui couldn't connect to ollama. 
I think I'm facing a similar issue here..any help/idea?

**Comment by pieroit** [comment]
Use docker host gateway, otherwise the cat sees "localhost" as the container itself

There should he an example in the docs

**Reply by b1tfl0w** [reply]
Thank you for your help, I really like this project!
ok..so I've added `network_mode: host` the compose.yml like this:

```
services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - 1865:80
      - 5678:5678
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
    network_mode: host
```
 
but now it works on port 80, I can reach the page at `http://debservr.local/admin` instead of `http://debservr.local:1865/admin/` in the log I see:
`! cheshire-cat-core Published ports are discarded when using host network mode`
is this ok or can create issues? I admit I'm a bit noob at using docker.
edit: ollama now works..

**Comment by b1tfl0w** [comment, marked as answer]
I solved this way:
```
services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - 1865:80
      - 5678:5678
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

and this as ollama address in settings:
`http://host.docker.internal:11434/`
