### ISSUE TITLE
[BUG] plugin page network error

### ISSUE THREAD

**Issue by Vincenzoferrara** [cheshire-cat-ai/core#1000]
I installed caddy on the machine and not in docker, here is the file:

```
#modificare questo nome hsot
https://stregatto-ai.local {

#tls internal #autocreato
    tls smallstep@smallstep.local {
        ca https://smallstep.local/acme/acme/directory
        ca_root /etc/caddy/root_ca.crt
    }
    reverse_proxy localhost:1865
}
```

I have a local ca authentication server created with smallstep.
to access cheshire-cat-ai I have a firewall activated port 443.80

my docker compose:

```
services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ports:
      - 1865:80
      - 5678:5678
    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
```

vm: debian 12
even disabling tls gives me the same error
if i bypass caddy it works

![streggato bug1](https://github.com/user-attachments/assets/2e1ea4f0-bddf-41df-b9c6-f45cd9540a63)
![streggato bug2](https://github.com/user-attachments/assets/159c1ea4-4246-43e5-ae25-e14a6f4814d6)
