### ISSUE TITLE
[Feature] Add support for self-hosted Llama2 out of the box

### ISSUE THREAD

**Issue by AlessandroSpallina** [cheshire-cat-ai/core#422]
**Is your feature request related to a problem? Please describe.**
As a user who is interested in using the Cat with a self-hosted Llama 2 model, at the moment, the only way to make it work is running a custom REST API server using that model as LLM behind. In order to run that server I should write myself a backend or find someone's else code. As a user, I would like to see in the Cat an easier way to use Llama as a local LLM.

**Describe the solution you'd like**
#### Backend
Add support to use Llama 2: accordingly to the current architecture, the LLM should be served from a REST API server, but we should "take the user by the hand" suggesting a more reliable approach reusing the best open-source option for that backend: [llama-cpp-python](https://github.com/abetlen/llama-cpp-python#web-server).
Llama-cpp-python provides python bindings for llama.cpp which is one of the best ways to use Llama 2 on-prem. This package ships also an OpenAI API-compatible REST server, so there is no need for a user to write a custom API server if the Cat supports integration with the llama-cpp-python server! The package is moreover already compatible with LangChain which is the current library used in the Cat to support all the LLMs currently usable. Integrating this proposal will not add any new dependency to the core and make it easier for a user to start playing with the Cat using a self-hosted LLM.

#### Frontend
In /admin/settings I would like to see a new line under "Configure the Language Model" like the image below
![image](https://github.com/cheshire-cat-ai/core/assets/10786872/063b2fe2-b238-4db1-b6bf-c7da39190066)

**Describe alternatives you've considered**
As said above, the alternative would be to let the user write/find a backend compatible with the Cat's Custom Model API ([here a crappy example](https://github.com/cheshire-cat-ai/core/issues/184#issuecomment-1685301450)), this should be considered related to advanced users and whenever an easier way appears this should be integrated in order to facilitate the setting process.

**Comment by valentimarco** [comment]
As discuss #184, the idea is to create special endpoint for custom LLM, so it's a good progress! i thought to work it so i can provide some help :)

**Comment by AlessandroSpallina** [comment]
> As discuss #184, the idea is to create special endpoint for custom LLM, so it's a good progress! i thought to work it so i can provide some help :)

I was thinking to get into the development starting from this improvement proposal, @valentimarco if you want we can work together on it, two brains are better than one joining for the first time a new codebase

**Comment by pieroit** [comment]
@AlessandroSpallina let's do this!!!

Please note that there are still lots of way to sefl host LLAMA, so let's call this adapter with the name of the lib itself. Something like `llama.cpp (python bindings)` or `Self hosted llama.cpp` or something similar. We can also signal that we support the library on their repo.

We'll provide the adapter and write an easy to follow tutorial to setup everything.
Question, does also `llama-cpp-python` work with GPUs?

Thanks

**Comment by AlessandroSpallina** [comment]
> does also `llama-cpp-python` work with GPUs?

Yup!

**Comment by pieroit** [comment]
I tried the lib, looks good. Next I'll try with GPU.
Here is a compose setup if it can be useful

```yaml

version: '3.7'

# run directly via docker:
# docker run --rm -it -p 8000:8000 -v ./models:/models -e MODEL=/models/llama-2-7b-chat.ggmlv3.q2_K.bin ghcr.io/abetlen/llama-cpp-python:latest

services:

  llama_cpp:
    container_name: llama_cpp
    image: ghcr.io/abetlen/llama-cpp-python:latest
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL=/models/llama-2-7b-chat.ggmlv3.q2_K.bin
    ports:
      - 8000:8000
    volumes:
      - ./models:/models
    restart: unless-stopped

```
