### ISSUE TITLE
[Feature] Improve docker by giving it some volumes

### ISSUE THREAD

**Issue by ngxson** [cheshire-cat-ai/core#646]
Here is the list of volume paths that I propose:

```
services:
  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    ...
    volumes:
      - cheshire-cat-data:/app/cat/data
      - cheshire-cat-plugins:/app/cat/plugins
    ...

volumes:
  - cheshire-cat-data
  - cheshire-cat-plugins
```
