### ISSUE TITLE
[BUG] Configuring Settings in Admin interface don't honor CORE_USE_SECURE_PROTOCOL=true in redirect

### ISSUE THREAD

**Issue by didn0t** [cheshire-cat-ai/core#674]
**Describe the bug**

I am running the ghcr.io/cheshire-cat-ai/core:latest docker container behind a traefik reverse proxy with TLS.  Attempts to save configuration items display "Network Error" in the web interface.  Looking at the HTTP requests the service is sending a redirect to the http:// URL.
  
**To Reproduce**
Steps to reproduce the behavior (as exampple`):

The following docker compose file is used:

```
version: '3.7'

services:

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:latest
    container_name: cheshire_cat_core
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=cc.mydomain.org
      - CORE_PORT=443
      - CORE_USE_SECURE_PROTOCOLS=true
        #      - LOG_LEVEL=DEBUG
        #      - DEBUG=true

    volumes:
      - ./static:/app/cat/static
      - ./plugins:/app/cat/plugins
      - ./data:/app/cat/data
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cheshirecat-rtr.entrypoints=internal"
        - "traefik.http.routers.cheshirecat-rtr.rule=Host(`cc.mydomain.org`)"
        - "traefik.http.routers.cheshirecat-rtr.tls=true"
        - "traefik.http.services.cheshirecat-svc.loadbalancer.server.port=80"
    logging:
      driver: journald

networks:
  default:
    external:
      name: proxy
```

**Expected behavior**
Settings should be saved correctly.

**Additional context**

### HTTP Request:

```
PUT /embedder/settings/EmbedderFakeConfig/ HTTP/1.1
Host: cc.mydomain.org
Connection: close
Content-Length: 12
user_id: user
sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Content-Type: application/json
Accept: application/json
access_token: 
sec-ch-ua-platform: "macOS"
Origin: https://cc.mydomain.org
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://cc.mydomain.org/admin/settings
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: [deleted]

{"size":128}
```

### HTTP Response:

```
HTTP/1.1 307 Temporary Redirect
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://cc.mydomain.org
Content-Length: 0
Date: Fri, 19 Jan 2024 11:23:46 GMT
Location: **http**://cc.mydomain.org/embedder/settings/EmbedderFakeConfig
Server: uvicorn
Vary: Origin
Connection: close
```
