### ISSUE TITLE
[BUG] sqlite3.OperationalError: cannot start a transaction within a transaction

### ISSUE THREAD

**Issue by ambitious-octopus** [cheshire-cat-ai/core#702]
**Describe the bug**
Uploading multiple documents (20+) result in: `sqlite3.OperationalError: cannot start a transaction within a transaction`. This may be related to the fact that sqlite does not support multiple write transaction. Quoting from the [docs](https://www.sqlite.org/lang_transaction.html):

> SQLite supports multiple simultaneous read transactions coming from separate database connections, possibly in separate threads or processes, but only one simultaneous write transaction.

**To Reproduce**
Steps to reproduce the behavior :
1. Open admin panel (`/admin`)
2. Load multiple documents 

**Expected behavior**
I expect the cat to write to database in batch memory by memory.

**Additional context**
Active plugins:
[Cheshire Cat ReRanker](Cheshire Cat ReRanker )
[C.A.T. - Cat Advanced Tools](https://github.com/Furrmidable-Crew/cat_advanced_tools)

If this feature is in development roadmap I can take care of it!

**Comment by valentimarco** [comment]
Hi thx for this bug report! Unfortunally the problem is well know to the community and qdrant. To resolve the issue, you need to instance a Qdrant DB, you can check this docker-compose file as example:
```yaml
version: '3.7'

services:
  cheshire-cat-core:
      image: ghcr.io/cheshire-cat-ai/core:latest
      container_name: cheshire_cat_core
      depends_on:
        - cheshire-cat-vector-memory
      environment:
        - PYTHONUNBUFFERED=1
        - WATCHFILES_FORCE_POLLING=true
        - CORE_HOST=${CORE_HOST:-localhost}
        - CORE_PORT=${CORE_PORT:-1865}
        - QDRANT_HOST=${QDRANT_HOST:-cheshire_cat_vector_memory}
        - QDRANT_PORT=${QDRANT_PORT:-6333}
        - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
        - API_KEY=${API_KEY:-}
        - LOG_LEVEL=${LOG_LEVEL:-WARNING}
        - DEBUG=${DEBUG:-true}
        - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
      ports:
        - ${CORE_PORT:-1865}:80
      volumes:
        - ./cat/static:/app/cat/static
        - ./cat/plugins:/app/cat/plugins
        - ./cat/data:/app/cat/data
        - ./cat/embedder:/app/local_cache
      restart: unless-stopped


  cheshire-cat-vector-memory:
    image: qdrant/qdrant:v1.6.1
    container_name: cheshire_cat_vector_memory
    expose:
      - 6333
    volumes:
      - ./cat/long_term_memory/vector:/qdrant/storage
    restart: unless-stopped
```
