### ISSUE TITLE
ENV variable for Qdrant endpoint doesn't seem to work 

### ISSUE THREAD

**Issue by designcomputer** [cheshire-cat-ai/core#726]
I am trying to connect a local instance of the Cheshire Cat AI (Version 1.4.8) running in Docker under Windows 10 Pro to a cloud instance of Qdrant.
 
Configuring the **.env** file as described in the documentation doesn't seem to work. I've placed the file below in the same directory as the **compose.yml** file. I've added the variables with and without quotes. 

re: [https://cheshire-cat-ai.github.io/docs/administrators/env-variables/?h=env](url)

Here is my .env file:

```
# Decide host and port for your Cat. Default will be localhost:1865
CORE_HOST=localhost
CORE_PORT=1865

# Qdrant server
QDRANT_HOST="https://therealcodegoeshere.us-east4-0.gcp.cloud.qdrant.io"
QDRANT_PORT=6333
QDRANT_API_KEY="therealAPIkeygoeshere"

# Decide to use https / wss secure protocols
#CORE_USE_SECURE_PROTOCOLS=true

# Protect endpoints with an access token
#API_KEY=meow

# Log levels
LOG_LEVEL=DEBUG

# Turn on memory collections' snapshots on embedder change with SAVE_MEMORY_SNAPSHOTS=true
SAVE_MEMORY_SNAPSHOTS=false
```
Restarting the container after making these additions doesn't seem to change anything. The locale Qdrant is still used.

```
PS I:\cheshire-cat-ai> docker compose up
[+] Running 1/0
 - Container cheshire_cat_core  Created                                                                            0.0s
Attaching to cheshire_cat_core
cheshire_cat_core  | INFO:     Will watch for changes in these directories: ['/app']
cheshire_cat_core  | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
cheshire_cat_core  | INFO:     Started reloader process [7] using WatchFiles
cheshire_cat_core  | INFO:     Started server process [23]
cheshire_cat_core  | INFO:     Waiting for application startup.
cheshire_cat_core  | [2024-02-19 21:39:50.317] INFO   cat.mad_hatter.mad_hatter.MadHatter.find_plugins::93
cheshire_cat_core  | "ACTIVE PLUGINS:"
cheshire_cat_core  | [2024-02-19 21:39:50.324] INFO   cat.mad_hatter.mad_hatter.MadHatter.find_plugins::94
cheshire_cat_core  | [
cheshire_cat_core  |     "core_plugin",
cheshire_cat_core  |     "cat_advanced_tools",
cheshire_cat_core  |     "curiouscat"
cheshire_cat_core  | ]
cheshire_cat_core  | [2024-02-19 21:39:50.505] INFO   cat.mad_hatter.plugin.Plugin._install_requirements::246
cheshire_cat_core  | "Installing requirements for: curiouscat"
cheshire_cat_core  | [2024-02-19 21:39:51.279] INFO   cat.memory.vector_memory.VectorMemory.connect_to_vector_memory::57

cheshire_cat_core  | "Qdrant path: cat/data/local_vector_memory/"
cheshire_cat_core  | [2024-02-19 21:39:51.316] INFO   cat.memory.vector_memory_collection.VectorMemoryCollection.create_db_collection_if_not_exists::94
cheshire_cat_core  | "Collection 'episodic' already present in vector store"
cheshire_cat_core  | [2024-02-19 21:39:51.341] INFO   cat.memory.vector_memory_collection.VectorMemoryCollection.create_db_collection_if_not_exists::94
cheshire_cat_core  | "Collection 'declarative' already present in vector store"
cheshire_cat_core  | [2024-02-19 21:39:51.365] INFO   cat.memory.vector_memory_collection.VectorMemoryCollection.create_db_collection_if_not_exists::94
cheshire_cat_core  | "Collection 'procedural' already present in vector store"
cheshire_cat_core  | INFO:     Application startup complete.
```

**Comment by valentimarco** [comment]
remove the "" in the .env

**Comment by designcomputer** [comment]
> remove the "" in the .env

I've tried it both ways and the results are the same.

**Comment by valentimarco** [comment]
uhm... can you check the docs of qdrant client python?

**Comment by pieroit** [comment]
> > remove the "" in the .env
> 
> I've tried it both ways and the results are the same.

Are you passing the env variable in the docker compose?

**Comment by designcomputer** [comment]
> > > remove the "" in the .env
> > 
> > 
> > I've tried it both ways and the results are the same.
> 
> Are you passing the env variable in the docker compose?

Just like it says in the docs:

"To set an environment variable, create a file with name .env at the same level of the docker-compose.yml file. The command docker compose up reads the .env file and sets the environment variable."

**Comment by valentimarco** [comment]
AH ok, so we remove qdrant and qdrant env from the docker-compose for windows problems. Follow this docker-compose:
 ```yml
cheshire-cat-core:
    image: <name of the image>
    container_name: cheshire_cat_core
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=${CORE_HOST:-localhost}
      - CORE_PORT=${CORE_PORT:-1865}
      - QDRANT_HOST=${QDRANT_HOST:-localhost}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - QDRANT_API_KEY=${QDRANT_API_KEY:-}
      - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
      - API_KEY=${API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-true}
      - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
    ports:
      - ${CORE_PORT:-1865}:80
    volumes:
      - ./core:/app
    command:
      - python
      - "-m"
      - "cat.main"
    restart: unless-stopped
```
